services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: seguros_sqlserver
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - ./data/sqlserver:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: seguros_rabbit
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
